# Generated by Petrodactal upgrade pack (CPU/RAM fields)
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverstatus",
            name="cpu_percent",
            field=models.FloatField(blank=True, help_text="CPU usage percent (resources.cpu_absolute).", null=True),
        ),
        migrations.AddField(
            model_name="serverstatus",
            name="memory_mb",
            field=models.IntegerField(blank=True, help_text="RAM usage MB (resources.memory_bytes / 1024 / 1024).", null=True),
        ),
    ]
